// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package ragit

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jryannel/sqlb"
)

type chunkColumns struct {
	ID                   sqlb.Col[uuid.UUID]
	DocumentID           sqlb.Col[uuid.UUID]
	TenantID             sqlb.Col[uuid.UUID]
	ScopeAID             sqlb.Col[uuid.UUID]
	ScopeBID             sqlb.Col[uuid.UUID]
	SessionID            sqlb.Col[uuid.UUID]
	ChunkIndex           sqlb.Col[int32]
	HeadingPath          sqlb.ArrayCol[string]
	Content              sqlb.TextCol[string]
	EmbeddingFingerprint sqlb.TextCol[string]
	Metadata             sqlb.Col[json.RawMessage]
	Attributes           sqlb.Col[json.RawMessage]
	ExpiresAt            sqlb.Col[time.Time]
	CreatedAt            sqlb.Col[time.Time]
}

// ChunkCols are the typed columns of ragit_chunks.
// Hidden columns are omitted: a predicate against one should not compile.
// Omitted here: embedding.
// Declaring LookupKey beside Hidden returns one to this facade, for the column
// whose own value is how the row is found. It stays off the wire either way.
var ChunkCols = chunkColumns{
	ID:                   sqlb.Typed[uuid.UUID]("id"),
	DocumentID:           sqlb.Typed[uuid.UUID]("document_id"),
	TenantID:             sqlb.Typed[uuid.UUID]("tenant_id"),
	ScopeAID:             sqlb.Typed[uuid.UUID]("scope_a_id"),
	ScopeBID:             sqlb.Typed[uuid.UUID]("scope_b_id"),
	SessionID:            sqlb.Typed[uuid.UUID]("session_id"),
	ChunkIndex:           sqlb.Typed[int32]("chunk_index"),
	HeadingPath:          sqlb.ArrayColumn[string]("heading_path"),
	Content:              sqlb.TextColumn[string]("content"),
	EmbeddingFingerprint: sqlb.TextColumn[string]("embedding_fingerprint"),
	Metadata:             sqlb.Typed[json.RawMessage]("metadata"),
	Attributes:           sqlb.Typed[json.RawMessage]("attributes"),
	ExpiresAt:            sqlb.Typed[time.Time]("expires_at"),
	CreatedAt:            sqlb.Typed[time.Time]("created_at"),
}

// ChunkUpdate is a typed update statement for ragit_chunks.
type ChunkUpdate struct {
	stmt *sqlb.Update[Chunk]
}

// UpdateChunk starts a typed update.
func UpdateChunk() *ChunkUpdate {
	return &ChunkUpdate{stmt: sqlb.UpdateRows[Chunk]()}
}

// SetDocumentID sets document_id.
func (u *ChunkUpdate) SetDocumentID(v uuid.UUID) *ChunkUpdate {
	u.stmt.Set("document_id", v)
	return u
}

// SetTenantID sets tenant_id.
func (u *ChunkUpdate) SetTenantID(v uuid.UUID) *ChunkUpdate {
	u.stmt.Set("tenant_id", v)
	return u
}

// SetScopeAID sets scope_a_id.
func (u *ChunkUpdate) SetScopeAID(v *uuid.UUID) *ChunkUpdate {
	u.stmt.Set("scope_a_id", v)
	return u
}

// SetScopeBID sets scope_b_id.
func (u *ChunkUpdate) SetScopeBID(v *uuid.UUID) *ChunkUpdate {
	u.stmt.Set("scope_b_id", v)
	return u
}

// SetSessionID sets session_id.
func (u *ChunkUpdate) SetSessionID(v *uuid.UUID) *ChunkUpdate {
	u.stmt.Set("session_id", v)
	return u
}

// SetChunkIndex sets chunk_index.
func (u *ChunkUpdate) SetChunkIndex(v int32) *ChunkUpdate {
	u.stmt.Set("chunk_index", v)
	return u
}

// SetHeadingPath sets heading_path.
func (u *ChunkUpdate) SetHeadingPath(v []string) *ChunkUpdate {
	u.stmt.Set("heading_path", v)
	return u
}

// SetContent sets content.
func (u *ChunkUpdate) SetContent(v string) *ChunkUpdate {
	u.stmt.Set("content", v)
	return u
}

// SetEmbedding sets embedding.
func (u *ChunkUpdate) SetEmbedding(v *sqlb.Vector) *ChunkUpdate {
	u.stmt.Set("embedding", v)
	return u
}

// SetEmbeddingFingerprint sets embedding_fingerprint.
func (u *ChunkUpdate) SetEmbeddingFingerprint(v *string) *ChunkUpdate {
	u.stmt.Set("embedding_fingerprint", v)
	return u
}

// SetMetadata sets metadata.
func (u *ChunkUpdate) SetMetadata(v json.RawMessage) *ChunkUpdate {
	u.stmt.Set("metadata", v)
	return u
}

// SetAttributes sets attributes.
func (u *ChunkUpdate) SetAttributes(v json.RawMessage) *ChunkUpdate {
	u.stmt.Set("attributes", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *ChunkUpdate) SetExpiresAt(v *time.Time) *ChunkUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *ChunkUpdate) SetCreatedAt(v time.Time) *ChunkUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// Where narrows the affected rows.
func (u *ChunkUpdate) Where(preds ...sqlb.Pred) *ChunkUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *ChunkUpdate) Stmt() *sqlb.Update[Chunk] { return u.stmt }

type documentColumns struct {
	ID             sqlb.Col[uuid.UUID]
	TenantID       sqlb.Col[uuid.UUID]
	ScopeAID       sqlb.Col[uuid.UUID]
	ScopeBID       sqlb.Col[uuid.UUID]
	SessionID      sqlb.Col[uuid.UUID]
	SourceURI      sqlb.TextCol[string]
	Filename       sqlb.TextCol[string]
	MimeType       sqlb.TextCol[string]
	Status         sqlb.TextCol[string]
	Error          sqlb.TextCol[string]
	TextContent    sqlb.TextCol[string]
	Metadata       sqlb.Col[json.RawMessage]
	Attributes     sqlb.Col[json.RawMessage]
	ChunkCount     sqlb.Col[int32]
	EmbeddingModel sqlb.TextCol[string]
	ProcessedAt    sqlb.Col[time.Time]
	ExpiresAt      sqlb.Col[time.Time]
	CreatedAt      sqlb.Col[time.Time]
	UpdatedAt      sqlb.Col[time.Time]
}

// DocumentCols are the typed columns of ragit_documents.
var DocumentCols = documentColumns{
	ID:             sqlb.Typed[uuid.UUID]("id"),
	TenantID:       sqlb.Typed[uuid.UUID]("tenant_id"),
	ScopeAID:       sqlb.Typed[uuid.UUID]("scope_a_id"),
	ScopeBID:       sqlb.Typed[uuid.UUID]("scope_b_id"),
	SessionID:      sqlb.Typed[uuid.UUID]("session_id"),
	SourceURI:      sqlb.TextColumn[string]("source_uri"),
	Filename:       sqlb.TextColumn[string]("filename"),
	MimeType:       sqlb.TextColumn[string]("mime_type"),
	Status:         sqlb.TextColumn[string]("status"),
	Error:          sqlb.TextColumn[string]("error"),
	TextContent:    sqlb.TextColumn[string]("text_content"),
	Metadata:       sqlb.Typed[json.RawMessage]("metadata"),
	Attributes:     sqlb.Typed[json.RawMessage]("attributes"),
	ChunkCount:     sqlb.Typed[int32]("chunk_count"),
	EmbeddingModel: sqlb.TextColumn[string]("embedding_model"),
	ProcessedAt:    sqlb.Typed[time.Time]("processed_at"),
	ExpiresAt:      sqlb.Typed[time.Time]("expires_at"),
	CreatedAt:      sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:      sqlb.Typed[time.Time]("updated_at"),
}

// DocumentUpdate is a typed update statement for ragit_documents.
type DocumentUpdate struct {
	stmt *sqlb.Update[Document]
}

// UpdateDocument starts a typed update.
func UpdateDocument() *DocumentUpdate {
	return &DocumentUpdate{stmt: sqlb.UpdateRows[Document]()}
}

// SetTenantID sets tenant_id.
func (u *DocumentUpdate) SetTenantID(v uuid.UUID) *DocumentUpdate {
	u.stmt.Set("tenant_id", v)
	return u
}

// SetScopeAID sets scope_a_id.
func (u *DocumentUpdate) SetScopeAID(v *uuid.UUID) *DocumentUpdate {
	u.stmt.Set("scope_a_id", v)
	return u
}

// SetScopeBID sets scope_b_id.
func (u *DocumentUpdate) SetScopeBID(v *uuid.UUID) *DocumentUpdate {
	u.stmt.Set("scope_b_id", v)
	return u
}

// SetSessionID sets session_id.
func (u *DocumentUpdate) SetSessionID(v *uuid.UUID) *DocumentUpdate {
	u.stmt.Set("session_id", v)
	return u
}

// SetSourceURI sets source_uri.
func (u *DocumentUpdate) SetSourceURI(v *string) *DocumentUpdate {
	u.stmt.Set("source_uri", v)
	return u
}

// SetFilename sets filename.
func (u *DocumentUpdate) SetFilename(v string) *DocumentUpdate {
	u.stmt.Set("filename", v)
	return u
}

// SetMimeType sets mime_type.
func (u *DocumentUpdate) SetMimeType(v string) *DocumentUpdate {
	u.stmt.Set("mime_type", v)
	return u
}

// SetStatus sets status.
func (u *DocumentUpdate) SetStatus(v string) *DocumentUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetError sets error.
func (u *DocumentUpdate) SetError(v *string) *DocumentUpdate {
	u.stmt.Set("error", v)
	return u
}

// SetTextContent sets text_content.
func (u *DocumentUpdate) SetTextContent(v *string) *DocumentUpdate {
	u.stmt.Set("text_content", v)
	return u
}

// SetMetadata sets metadata.
func (u *DocumentUpdate) SetMetadata(v json.RawMessage) *DocumentUpdate {
	u.stmt.Set("metadata", v)
	return u
}

// SetAttributes sets attributes.
func (u *DocumentUpdate) SetAttributes(v json.RawMessage) *DocumentUpdate {
	u.stmt.Set("attributes", v)
	return u
}

// SetChunkCount sets chunk_count.
func (u *DocumentUpdate) SetChunkCount(v *int32) *DocumentUpdate {
	u.stmt.Set("chunk_count", v)
	return u
}

// SetEmbeddingModel sets embedding_model.
func (u *DocumentUpdate) SetEmbeddingModel(v *string) *DocumentUpdate {
	u.stmt.Set("embedding_model", v)
	return u
}

// SetProcessedAt sets processed_at.
func (u *DocumentUpdate) SetProcessedAt(v *time.Time) *DocumentUpdate {
	u.stmt.Set("processed_at", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *DocumentUpdate) SetExpiresAt(v *time.Time) *DocumentUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *DocumentUpdate) SetCreatedAt(v time.Time) *DocumentUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *DocumentUpdate) SetUpdatedAt(v time.Time) *DocumentUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *DocumentUpdate) Where(preds ...sqlb.Pred) *DocumentUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *DocumentUpdate) Stmt() *sqlb.Update[Document] { return u.stmt }
