package ragit

import (
	"context"
	"io/fs"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/mind-vm/ragit/internal/migrate"
	"github.com/mind-vm/ragit/migrations"
)

// MigrationsTable is the schema-version table ragit tracks its own migration
// line in, deliberately not goose's default goose_db_version.
//
// It is exported because a consumer applying a rendered migration set with
// their own tooling has to name it, and guessing wrong is silent: goose starts
// a second history in goose_db_version and re-applies migrations the database
// already has. Prefer [Migrate] with [FromFS], which knows it.
const MigrationsTable = migrate.TableName

// MigrateOption configures where [Migrate] and [MigrateDown] read their SQL.
type MigrateOption func(*migrateConfig)

type migrateConfig struct{ fsys fs.FS }

// FromFS applies a migration set rendered by cmd/ragit-gen instead of the one
// embedded in this build.
//
// This is the path for a corpus at a different embedding dimension. A vector
// column's width is part of its type, so an embedder that is not 1536-wide
// needs its own rendered schema:
//
//	//go:embed *.sql
//	var migrationsFS embed.FS
//
//	err := ragit.Migrate(ctx, pool, ragit.FromFS(migrationsFS))
//
// generated by:
//
//	go run github.com/mind-vm/ragit/cmd/ragit-gen -dim 768 -migrations ./migrations -skip-models
//
// The models need no such treatment — Chunk.Embedding is a *sqlb.Vector
// whatever the width — so only the SQL differs.
//
// Applying a set at one width to a database created at another is refused
// rather than skipped: every rendered set carries the same version numbers, so
// goose would otherwise find them already applied and report success having
// changed nothing.
func FromFS(fsys fs.FS) MigrateOption {
	return func(c *migrateConfig) { c.fsys = fsys }
}

func (c migrateConfig) source() fs.FS {
	if c.fsys != nil {
		return c.fsys
	}
	return migrations.FS
}

func newMigrateConfig(opts []MigrateOption) migrateConfig {
	var c migrateConfig
	for _, opt := range opts {
		opt(&c)
	}
	return c
}

// Migrate brings ragit's own tables up to the schema this build expects.
//
// ragit owns its migration line rather than shipping loose .sql files for a
// host application to vendor into its own sequence: the migrations are
// embedded in the binary and tracked in a ragit_migrations version table, so
// upgrading the library upgrades its schema, and a host app's own migration
// tool never has to know these tables exist. This mirrors how River manages
// its river_* tables.
//
// It is safe to call on every startup, and touches nothing outside the
// ragit_-prefixed tables.
//
// [FromFS] points it at a set rendered at another embedding dimension, so a
// consumer at a width other than the default does not have to re-implement the
// runner — or remember [MigrationsTable].
//
// The connecting role must not be a superuser if the row-level security
// policies are to have any effect — PostgreSQL exempts superusers from RLS
// entirely, FORCE or not. Migrating as an admin role and then running the
// application as an ordinary one is the intended split.
func Migrate(ctx context.Context, pool *pgxpool.Pool, opts ...MigrateOption) error {
	return migrate.Up(ctx, pool, newMigrateConfig(opts).source())
}

// MigrateDown rolls back the most recent migration. Intended for development
// and tests; rolling back a populated vector index rarely is what you want in
// production.
func MigrateDown(ctx context.Context, pool *pgxpool.Pool, opts ...MigrateOption) error {
	return migrate.Down(ctx, pool, newMigrateConfig(opts).source())
}
