-- Generated by sqlb. Review before applying.

-- +goose Up
-- vector extension, required by a column type or constraint declared below
CREATE EXTENSION IF NOT EXISTS "vector";
-- create table ragit_chunks
-- +goose StatementBegin
CREATE TABLE "ragit_chunks" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "document_id" uuid NOT NULL,
    "tenant_id" uuid NOT NULL,
    "scope_a_id" uuid,
    "scope_b_id" uuid,
    "session_id" uuid,
    "chunk_index" integer NOT NULL,
    "heading_path" text[],
    "content" text NOT NULL,
    "embedding" vector(1536),
    "embedding_fingerprint" text,
    "metadata" jsonb NOT NULL DEFAULT '{}',
    "expires_at" timestamptz,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "ragit_chunks_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "ragit_chunks" IS 'One retrieval-sized piece of a document, with its embedding.';
-- +goose StatementEnd
-- create table ragit_documents
-- +goose StatementBegin
CREATE TABLE "ragit_documents" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "tenant_id" uuid NOT NULL,
    "scope_a_id" uuid,
    "scope_b_id" uuid,
    "session_id" uuid,
    "source_uri" text,
    "filename" text NOT NULL,
    "mime_type" text NOT NULL,
    "status" text NOT NULL DEFAULT 'pending',
    "error" text,
    "text_content" text,
    "metadata" jsonb NOT NULL DEFAULT '{}',
    "chunk_count" integer,
    "embedding_model" text,
    "processed_at" timestamptz,
    "expires_at" timestamptz,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "ragit_documents_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "ragit_documents" IS 'A source document ingested by ragit.';
COMMENT ON COLUMN "ragit_documents"."status" IS 'pending|processing|ready|error|skipped_too_large';
-- +goose StatementEnd
-- add foreign key ragit_chunks_document_id_fkey
ALTER TABLE "ragit_chunks" ADD CONSTRAINT "ragit_chunks_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "ragit_documents" ("id") ON DELETE CASCADE;
-- index idx_ragit_chunks_embedding_hnsw
CREATE INDEX "idx_ragit_chunks_embedding_hnsw" ON "ragit_chunks" USING hnsw ("embedding" vector_cosine_ops) WITH (ef_construction = 64, m = 16);
-- index idx_ragit_chunks_expires_at
CREATE INDEX "idx_ragit_chunks_expires_at" ON "ragit_chunks" ("expires_at") WHERE expires_at IS NOT NULL;
-- index idx_ragit_chunks_session_id
CREATE INDEX "idx_ragit_chunks_session_id" ON "ragit_chunks" ("session_id") WHERE session_id IS NOT NULL;
-- index ragit_chunks_document_id_idx
CREATE INDEX "ragit_chunks_document_id_idx" ON "ragit_chunks" ("document_id");
-- index ragit_chunks_tenant_id_embedding_fingerprint_idx
CREATE INDEX "ragit_chunks_tenant_id_embedding_fingerprint_idx" ON "ragit_chunks" ("tenant_id", "embedding_fingerprint");
-- index ragit_chunks_tenant_id_idx
CREATE INDEX "ragit_chunks_tenant_id_idx" ON "ragit_chunks" ("tenant_id");
-- index ragit_chunks_tenant_id_scope_a_id_idx
CREATE INDEX "ragit_chunks_tenant_id_scope_a_id_idx" ON "ragit_chunks" ("tenant_id", "scope_a_id");
-- index ragit_chunks_tenant_id_scope_b_id_idx
CREATE INDEX "ragit_chunks_tenant_id_scope_b_id_idx" ON "ragit_chunks" ("tenant_id", "scope_b_id");
-- index idx_ragit_documents_expires_at
CREATE INDEX "idx_ragit_documents_expires_at" ON "ragit_documents" ("expires_at") WHERE expires_at IS NOT NULL;
-- index ragit_documents_tenant_id_idx
CREATE INDEX "ragit_documents_tenant_id_idx" ON "ragit_documents" ("tenant_id");
-- index ragit_documents_tenant_id_scope_a_id_idx
CREATE INDEX "ragit_documents_tenant_id_scope_a_id_idx" ON "ragit_documents" ("tenant_id", "scope_a_id");
-- index ragit_documents_tenant_id_scope_b_id_idx
CREATE INDEX "ragit_documents_tenant_id_scope_b_id_idx" ON "ragit_documents" ("tenant_id", "scope_b_id");

-- +goose Down
DROP INDEX "ragit_documents_tenant_id_scope_b_id_idx";
DROP INDEX "ragit_documents_tenant_id_scope_a_id_idx";
DROP INDEX "ragit_documents_tenant_id_idx";
DROP INDEX "idx_ragit_documents_expires_at";
DROP INDEX "ragit_chunks_tenant_id_scope_b_id_idx";
DROP INDEX "ragit_chunks_tenant_id_scope_a_id_idx";
DROP INDEX "ragit_chunks_tenant_id_idx";
DROP INDEX "ragit_chunks_tenant_id_embedding_fingerprint_idx";
DROP INDEX "ragit_chunks_document_id_idx";
DROP INDEX "idx_ragit_chunks_session_id";
DROP INDEX "idx_ragit_chunks_expires_at";
DROP INDEX "idx_ragit_chunks_embedding_hnsw";
ALTER TABLE "ragit_chunks" DROP CONSTRAINT "ragit_chunks_document_id_fkey";
DROP TABLE "ragit_documents";
DROP TABLE "ragit_chunks";
-- Not reversible automatically: no reverse SQL was generated for this change
