// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	pgvector_go "github.com/pgvector/pgvector-go"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createChunks = `-- name: CreateChunks :batchexec
INSERT INTO ragit_chunks (
  document_id, tenant_id, scope_id, session_id, chunk_index, heading_path,
  content, embedding, embedding_fingerprint, metadata
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateChunksBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateChunksParams struct {
	DocumentID           uuid.UUID           `json:"document_id"`
	TenantID             uuid.UUID           `json:"tenant_id"`
	ScopeID              *uuid.UUID          `json:"scope_id"`
	SessionID            *uuid.UUID          `json:"session_id"`
	ChunkIndex           int32               `json:"chunk_index"`
	HeadingPath          []string            `json:"heading_path"`
	Content              string              `json:"content"`
	Embedding            *pgvector_go.Vector `json:"embedding"`
	EmbeddingFingerprint *string             `json:"embedding_fingerprint"`
	Metadata             json.RawMessage     `json:"metadata"`
}

// Deliberately :batchexec and not :copyfrom. PostgreSQL rejects COPY FROM
// outright on a table with row-level security enabled ("COPY FROM not
// supported with row-level security"), which ragit_chunks has. A pgx batch
// is one round-trip anyway, and batches here are embedBatchSize-sized.
func (q *Queries) CreateChunks(ctx context.Context, arg []CreateChunksParams) *CreateChunksBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DocumentID,
			a.TenantID,
			a.ScopeID,
			a.SessionID,
			a.ChunkIndex,
			a.HeadingPath,
			a.Content,
			a.Embedding,
			a.EmbeddingFingerprint,
			a.Metadata,
		}
		batch.Queue(createChunks, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateChunksBatchResults{br, len(arg), false}
}

func (b *CreateChunksBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateChunksBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
