// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type CreateChunksParams struct {
	DocumentID           uuid.UUID           `json:"document_id"`
	TenantID             uuid.UUID           `json:"tenant_id"`
	ChunkIndex           int32               `json:"chunk_index"`
	HeadingPath          []string            `json:"heading_path"`
	Content              string              `json:"content"`
	Embedding            *pgvector_go.Vector `json:"embedding"`
	EmbeddingFingerprint *string             `json:"embedding_fingerprint"`
	Metadata             json.RawMessage     `json:"metadata"`
}

const getChunksByDocumentID = `-- name: GetChunksByDocumentID :many
SELECT id, document_id, tenant_id, chunk_index, heading_path, content, embedding, embedding_fingerprint, search_vector, metadata, created_at FROM chunks WHERE document_id = $1 AND tenant_id = $2 ORDER BY chunk_index ASC
`

type GetChunksByDocumentIDParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetChunksByDocumentID(ctx context.Context, arg GetChunksByDocumentIDParams) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, getChunksByDocumentID, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.ChunkIndex,
			&i.HeadingPath,
			&i.Content,
			&i.Embedding,
			&i.EmbeddingFingerprint,
			&i.SearchVector,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
