// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateChunks implements pgx.CopyFromSource.
type iteratorForCreateChunks struct {
	rows                 []CreateChunksParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateChunks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateChunks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DocumentID,
		r.rows[0].TenantID,
		r.rows[0].ChunkIndex,
		r.rows[0].HeadingPath,
		r.rows[0].Content,
		r.rows[0].Embedding,
		r.rows[0].EmbeddingFingerprint,
		r.rows[0].Metadata,
	}, nil
}

func (r iteratorForCreateChunks) Err() error {
	return nil
}

func (q *Queries) CreateChunks(ctx context.Context, arg []CreateChunksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"chunks"}, []string{"document_id", "tenant_id", "chunk_index", "heading_path", "content", "embedding", "embedding_fingerprint", "metadata"}, &iteratorForCreateChunks{rows: arg})
}
