// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
  tenant_id, source_uri, filename, mime_type
) VALUES (
  $1, $2, $3, $4
) RETURNING id, tenant_id, source_uri, filename, mime_type, status, error, text_content, metadata, chunk_count, embedding_model, processed_at, created_at, updated_at
`

type CreateDocumentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SourceUri *string   `json:"source_uri"`
	Filename  string    `json:"filename"`
	MimeType  string    `json:"mime_type"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TenantID,
		arg.SourceUri,
		arg.Filename,
		arg.MimeType,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceUri,
		&i.Filename,
		&i.MimeType,
		&i.Status,
		&i.Error,
		&i.TextContent,
		&i.Metadata,
		&i.ChunkCount,
		&i.EmbeddingModel,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, tenant_id, source_uri, filename, mime_type, status, error, text_content, metadata, chunk_count, embedding_model, processed_at, created_at, updated_at FROM documents WHERE id = $1 AND tenant_id = $2
`

type GetDocumentByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.TenantID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceUri,
		&i.Filename,
		&i.MimeType,
		&i.Status,
		&i.Error,
		&i.TextContent,
		&i.Metadata,
		&i.ChunkCount,
		&i.EmbeddingModel,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentError = `-- name: UpdateDocumentError :exec
UPDATE documents SET
  status = 'error',
  error = $2,
  updated_at = now()
WHERE id = $1
`

type UpdateDocumentErrorParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) UpdateDocumentError(ctx context.Context, arg UpdateDocumentErrorParams) error {
	_, err := q.db.Exec(ctx, updateDocumentError, arg.ID, arg.Error)
	return err
}

const updateDocumentProcessing = `-- name: UpdateDocumentProcessing :exec
UPDATE documents SET status = 'processing', updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateDocumentProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateDocumentProcessing, id)
	return err
}

const updateDocumentReady = `-- name: UpdateDocumentReady :exec
UPDATE documents SET
  status = 'ready',
  text_content = $2,
  metadata = $3,
  chunk_count = $4,
  embedding_model = $5,
  processed_at = $6,
  updated_at = now()
WHERE id = $1
`

type UpdateDocumentReadyParams struct {
	ID             uuid.UUID       `json:"id"`
	TextContent    *string         `json:"text_content"`
	Metadata       json.RawMessage `json:"metadata"`
	ChunkCount     *int32          `json:"chunk_count"`
	EmbeddingModel *string         `json:"embedding_model"`
	ProcessedAt    *time.Time      `json:"processed_at"`
}

func (q *Queries) UpdateDocumentReady(ctx context.Context, arg UpdateDocumentReadyParams) error {
	_, err := q.db.Exec(ctx, updateDocumentReady,
		arg.ID,
		arg.TextContent,
		arg.Metadata,
		arg.ChunkCount,
		arg.EmbeddingModel,
		arg.ProcessedAt,
	)
	return err
}
