// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO ragit_documents (
  tenant_id, scope_id, session_id, source_uri, filename, mime_type, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, scope_id, session_id, source_uri, filename, mime_type, status, error, text_content, metadata, chunk_count, embedding_model, processed_at, created_at, updated_at, expires_at
`

type CreateDocumentParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	ScopeID   *uuid.UUID `json:"scope_id"`
	SessionID *uuid.UUID `json:"session_id"`
	SourceUri *string    `json:"source_uri"`
	Filename  string     `json:"filename"`
	MimeType  string     `json:"mime_type"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TenantID,
		arg.ScopeID,
		arg.SessionID,
		arg.SourceUri,
		arg.Filename,
		arg.MimeType,
		arg.ExpiresAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeID,
		&i.SessionID,
		&i.SourceUri,
		&i.Filename,
		&i.MimeType,
		&i.Status,
		&i.Error,
		&i.TextContent,
		&i.Metadata,
		&i.ChunkCount,
		&i.EmbeddingModel,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM ragit_documents WHERE id = $1 AND tenant_id = $2
`

type DeleteDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Cascades to ragit_chunks via the FK in migration 00001.
func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.TenantID)
	return err
}

const deleteDocumentsByIDs = `-- name: DeleteDocumentsByIDs :execrows
DELETE FROM ragit_documents WHERE id = ANY($1::uuid[])
`

// Cascades to ragit_chunks via the FK in migration 00001.
func (q *Queries) DeleteDocumentsByIDs(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocumentsByIDs, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredChunks = `-- name: DeleteExpiredChunks :execrows
DELETE FROM ragit_chunks WHERE expires_at IS NOT NULL AND expires_at <= now()
`

// Chunks can outlive their document's retention clock when only the chunks
// were given one (an attachment whose source file is still wanted). Runs
// after the document sweep so it only sees genuinely orphaned expiries.
func (q *Queries) DeleteExpiredChunks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChunks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, tenant_id, scope_id, session_id, source_uri, filename, mime_type, status, error, text_content, metadata, chunk_count, embedding_model, processed_at, created_at, updated_at, expires_at FROM ragit_documents WHERE id = $1 AND tenant_id = $2
`

type GetDocumentByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.TenantID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeID,
		&i.SessionID,
		&i.SourceUri,
		&i.Filename,
		&i.MimeType,
		&i.Status,
		&i.Error,
		&i.TextContent,
		&i.Metadata,
		&i.ChunkCount,
		&i.EmbeddingModel,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredDocuments = `-- name: ListExpiredDocuments :many
SELECT id, tenant_id, source_uri
FROM ragit_documents
WHERE expires_at IS NOT NULL AND expires_at <= now()
ORDER BY expires_at ASC
LIMIT $1::int
`

type ListExpiredDocumentsRow struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	SourceUri *string   `json:"source_uri"`
}

// Cross-tenant by design: the retention sweep cannot enumerate the tenants
// that own expired rows without first reading across tenants. Runs under
// db.WithMaintenance, which is the only place the maintenance GUC is set.
func (q *Queries) ListExpiredDocuments(ctx context.Context, resultLimit int32) ([]ListExpiredDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredDocuments, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredDocumentsRow{}
	for rows.Next() {
		var i ListExpiredDocumentsRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.SourceUri); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentError = `-- name: UpdateDocumentError :exec
UPDATE ragit_documents SET
  status = 'error',
  error = $2,
  updated_at = now()
WHERE id = $1
`

type UpdateDocumentErrorParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) UpdateDocumentError(ctx context.Context, arg UpdateDocumentErrorParams) error {
	_, err := q.db.Exec(ctx, updateDocumentError, arg.ID, arg.Error)
	return err
}

const updateDocumentProcessing = `-- name: UpdateDocumentProcessing :exec

UPDATE ragit_documents SET status = 'processing', updated_at = now() WHERE id = $1
`

// The Update* statements below filter on id alone. That is safe because
// every one of them runs inside a WithTenant transaction, where the
// ragit_documents RLS policy adds the tenant predicate itself; an id
// belonging to another tenant matches zero rows.
func (q *Queries) UpdateDocumentProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateDocumentProcessing, id)
	return err
}

const updateDocumentReady = `-- name: UpdateDocumentReady :exec
UPDATE ragit_documents SET
  status = 'ready',
  text_content = $2,
  metadata = $3,
  chunk_count = $4,
  embedding_model = $5,
  processed_at = $6,
  updated_at = now()
WHERE id = $1
`

type UpdateDocumentReadyParams struct {
	ID             uuid.UUID       `json:"id"`
	TextContent    *string         `json:"text_content"`
	Metadata       json.RawMessage `json:"metadata"`
	ChunkCount     *int32          `json:"chunk_count"`
	EmbeddingModel *string         `json:"embedding_model"`
	ProcessedAt    *time.Time      `json:"processed_at"`
}

func (q *Queries) UpdateDocumentReady(ctx context.Context, arg UpdateDocumentReadyParams) error {
	_, err := q.db.Exec(ctx, updateDocumentReady,
		arg.ID,
		arg.TextContent,
		arg.Metadata,
		arg.ChunkCount,
		arg.EmbeddingModel,
		arg.ProcessedAt,
	)
	return err
}

const updateDocumentScope = `-- name: UpdateDocumentScope :exec
UPDATE ragit_documents SET
  scope_id = $2,
  session_id = $3,
  updated_at = now()
WHERE id = $1
`

type UpdateDocumentScopeParams struct {
	ID        uuid.UUID  `json:"id"`
	ScopeID   *uuid.UUID `json:"scope_id"`
	SessionID *uuid.UUID `json:"session_id"`
}

// Moves a document between scopes. Callers must follow this with
// ResyncChunkScope — the chunks' denormalized copies do not self-heal.
func (q *Queries) UpdateDocumentScope(ctx context.Context, arg UpdateDocumentScopeParams) error {
	_, err := q.db.Exec(ctx, updateDocumentScope, arg.ID, arg.ScopeID, arg.SessionID)
	return err
}

const updateDocumentSkippedTooLarge = `-- name: UpdateDocumentSkippedTooLarge :exec
UPDATE ragit_documents SET
  status = 'skipped_too_large',
  error = $2,
  chunk_count = 0,
  updated_at = now()
WHERE id = $1
`

type UpdateDocumentSkippedTooLargeParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) UpdateDocumentSkippedTooLarge(ctx context.Context, arg UpdateDocumentSkippedTooLargeParams) error {
	_, err := q.db.Exec(ctx, updateDocumentSkippedTooLarge, arg.ID, arg.Error)
	return err
}
