// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID                   uuid.UUID           `json:"id"`
	DocumentID           uuid.UUID           `json:"document_id"`
	TenantID             uuid.UUID           `json:"tenant_id"`
	ScopeID              *uuid.UUID          `json:"scope_id"`
	SessionID            *uuid.UUID          `json:"session_id"`
	ChunkIndex           int32               `json:"chunk_index"`
	HeadingPath          []string            `json:"heading_path"`
	Content              string              `json:"content"`
	Embedding            *pgvector_go.Vector `json:"embedding"`
	EmbeddingFingerprint *string             `json:"embedding_fingerprint"`
	SearchVector         interface{}         `json:"search_vector"`
	Metadata             json.RawMessage     `json:"metadata"`
	CreatedAt            time.Time           `json:"created_at"`
}

type Document struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	ScopeID        *uuid.UUID      `json:"scope_id"`
	SessionID      *uuid.UUID      `json:"session_id"`
	SourceUri      *string         `json:"source_uri"`
	Filename       string          `json:"filename"`
	MimeType       string          `json:"mime_type"`
	Status         string          `json:"status"`
	Error          *string         `json:"error"`
	TextContent    *string         `json:"text_content"`
	Metadata       json.RawMessage `json:"metadata"`
	ChunkCount     *int32          `json:"chunk_count"`
	EmbeddingModel *string         `json:"embedding_model"`
	ProcessedAt    *time.Time      `json:"processed_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
