// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChunks(ctx context.Context, arg []CreateChunksParams) (int64, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	GetChunksByDocumentID(ctx context.Context, arg GetChunksByDocumentIDParams) ([]Chunk, error)
	GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error)
	UpdateDocumentError(ctx context.Context, arg UpdateDocumentErrorParams) error
	UpdateDocumentProcessing(ctx context.Context, id uuid.UUID) error
	UpdateDocumentReady(ctx context.Context, arg UpdateDocumentReadyParams) error
}

var _ Querier = (*Queries)(nil)
